# fly.toml app configuration file generated for sshcard on 2025-04-01T09:34:45Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sshcard'
primary_region = 'waw'

[build]
  [build.args]
    GO_VERSION = '1.24.0'

[[services]]
  internal_port = 23234
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  [[services.ports]]
    port = 22

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = "ssh_key"
  destination = "/data"
